=== Emergya/opensir/sir-admin/sir-admin-extensions/subdere-db-migration/src/test/resources/datasets/usuarios.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT dataset (
    gis_authority_type|
    gis_sector|
    gis_permission|
    gis_permission_by_authtype|
    gis_zone|
    gis_authority|
    gis_user|
    gis_file_type|
    gis_file_column|
    gis_layer_type|
    gis_layer_type_property|
    gis_property_in_layer_type|
    gis_folder|
    gis_layer|
    gis_layer_property|
    gis_layer_gis_layer_property
)*>
 
<!ELEMENT gis_user EMPTY>
<!ATTLIST gis_user
    id  CDATA #REQUIRED
    admin CDATA #IMPLIED
    apellidos CDATA #IMPLIED
    create_date CDATA #IMPLIED
    email CDATA #IMPLIED
    nombre_completo CDATA #IMPLIED
    password  CDATA #REQUIRED
    telefono CDATA #IMPLIED
    update_date CDATA #IMPLIED    
    username  CDATA #REQUIRED    
    valid CDATA #IMPLIED
    user_authority_id CDATA #IMPLIED
>

<!ELEMENT gis_zone EMPTY>
<!ATTLIST gis_zone
    id CDATA #REQUIRED
    code CDATA #IMPLIED
    create_date CDATA #IMPLIED
    name CDATA #IMPLIED
    type CDATA #IMPLIED
    update_date CDATA #IMPLIED
    nivelpadre_id CDATA #IMPLIED 
    enabled CDATA #REQUIRED   
>

<!ELEMENT gis_authority EMPTY>
<!ATTLIST gis_authority
    id CDATA #REQUIRED
    create_date CDATA #IMPLIED
    name CDATA #REQUIRED
    update_date CDATA #IMPLIED
    auth_type_id CDATA #IMPLIED
    zone_id CDATA #IMPLIED
>

<!ELEMENT gis_permission EMPTY>
<!ATTLIST gis_permission
    id CDATA #REQUIRED
    create_date CDATA #IMPLIED
    name_permission CDATA #IMPLIED
    update_date CDATA #IMPLIED
>

<!ELEMENT gis_permission_by_authtype EMPTY>
<!ATTLIST gis_permission_by_authtype
    auth_type_id CDATA #REQUIRED
    permission_id CDATA #REQUIRED
>

<!ELEMENT gis_sector EMPTY>
<!ATTLIST gis_sector
    id CDATA #REQUIRED
    nombre CDATA #IMPLIED
    create_date CDATA #IMPLIED
    update_date CDATA #IMPLIED
>

<!ELEMENT gis_authority_type EMPTY>
<!ATTLIST gis_authority_type
    id CDATA #REQUIRED
    citizen CDATA #IMPLIED
    create_date CDATA #IMPLIED
    name_auth_type CDATA #REQUIRED
    update_date CDATA #IMPLIED
>

<!ELEMENT gis_file_type EMPTY>
<!ATTLIST gis_file_type
    id CDATA #REQUIRED
    type_name CDATA #REQUIRED
    table_name CDATA #IMPLIED
    create_date CDATA #IMPLIED
    update_date CDATA #IMPLIED
>

<!ELEMENT gis_file_column EMPTY>
<!ATTLIST gis_file_column
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    dbname CDATA #REQUIRED
    filetype_id CDATA #REQUIRED 
    create_date CDATA #IMPLIED
    update_date CDATA #IMPLIED
>

<!ELEMENT gis_layer_type EMPTY>
<!ATTLIST gis_layer_type
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	tipo CDATA #REQUIRED
>

<!ELEMENT gis_layer_type_property EMPTY>
<!ATTLIST gis_layer_type_property
       id CDATA #REQUIRED
       name CDATA #REQUIRED
>
       
<!ELEMENT gis_property_in_layer_type EMPTY>
<!ATTLIST gis_property_in_layer_type
       layer_type CDATA #REQUIRED
       property CDATA #REQUIRED
>
	
<!ELEMENT gis_folder EMPTY>
<!ATTLIST gis_folder
	id CDATA #REQUIRED
    name CDATA #REQUIRED
	folder_zone_id CDATA #IMPLIED
	folder_parent_id CDATA #IMPLIED
	is_channel CDATA #IMPLIED
	is_plain CDATA #IMPLIED
    enabled CDATA #REQUIRED
    create_date CDATA #IMPLIED
>
    
    
<!ELEMENT gis_layer EMPTY>
<!ATTLIST gis_layer
    id CDATA #REQUIRED
    name_layer CDATA #REQUIRED
    enabled CDATA #REQUIRED
    server_resource CDATA #IMPLIED
    publicized CDATA #IMPLIED
    order_layer CDATA #IMPLIED
    is_channel CDATA #IMPLIED
    creat_date CDATA #IMPLIED
    update_date CDATA #IMPLIED
    layer_user_id CDATA #IMPLIED
    layer_auth_id CDATA #IMPLIED
    layer_folder_id CDATA #IMPLIED
    layer_layer_type_id CDATA #IMPLIED
>



<!ELEMENT gis_layer_property EMPTY>
<!ATTLIST gis_layer_property
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    value CDATA #REQUIRED
>

<!ELEMENT gis_layer_gis_layer_property EMPTY>
<!ATTLIST gis_layer_gis_layer_property
    gis_layer_id CDATA #REQUIRED
    properties_id CDATA #REQUIRED
>

=== Emergya/opensir/sir-admin/sir-admin-extensions/subdere-db-migration/src/test/resources/datasets/dataset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "usuarios.dtd" >
<dataset>

    <!-- Tipos de institución -->
    <gis_authority_type name_auth_type="Municipalidad" id="1"
        citizen="false" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_authority_type name_auth_type="Servicio Público" id="2"
        citizen="false" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_authority_type name_auth_type="Otros" id="3"
        citizen="false" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_authority_type name_auth_type="Ciudadano" id="4"
        citizen="true" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />


    <!-- Sectores -->
    <gis_sector id="1" nombre="Salud" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_sector id="2" nombre="Educación" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_sector id="3" nombre="Comercio" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_sector id="4" nombre="Turismo" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_sector id="5" nombre="Industria" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />
    <gis_sector id="6" nombre="Agricultura" update_date="2012-10-02 16:27:49.250453"
        create_date="2012-10-02 16:27:49.250453" />


    <!-- Permisos -->
    <gis_permission id="1" name_permission="Permiso1"
        create_date="2012-10-02 16:27:49.250453" update_date="2012-10-02 16:27:49.250453" />
    <gis_permission id="2" name_permission="Permiso2"
        create_date="2012-10-02 16:27:49.250453" update_date="2012-10-02 16:27:49.250453" />
    <gis_permission id="3" name_permission="Permiso3"
        create_date="2012-10-02 16:27:49.250453" update_date="2012-10-02 16:27:49.250453" />
    <gis_permission id="4" name_permission="Permiso4"
        create_date="2012-10-02 16:27:49.250453" update_date="2012-10-02 16:27:49.250453" />
    <gis_permission id="5" name_permission="Permiso5"
        create_date="2012-10-02 16:27:49.250453" update_date="2012-10-02 16:27:49.250453" />


    <!-- Permisos por tipo de institución -->
    <gis_permission_by_authtype permission_id="2"
        auth_type_id="1" />
    <gis_permission_by_authtype permission_id="4"
        auth_type_id="1" />
    <gis_permission_by_authtype permission_id="5"
        auth_type_id="2" />
    <gis_permission_by_authtype permission_id="1"
        auth_type_id="2" />
    <gis_permission_by_authtype permission_id="5"
        auth_type_id="3" />
    <gis_permission_by_authtype permission_id="3"
        auth_type_id="4" />
    <gis_permission_by_authtype permission_id="1"
        auth_type_id="4" />



    <!-- Ámbito territorial -->
    <gis_zone enabled="true" id="1" code="1"
        name="O'Higgins" type="R" />
    <gis_zone enabled="true" id="2" code="2"
        name="Cachacoal" type="P" nivelpadre_id="1"/>
    <gis_zone enabled="true" id="3" code="3"
        name="Colchagua" type="P" nivelpadre_id="1"/>
    <gis_zone enabled="true" id="4" code="4"
        name="Cardenal Caro" type="P" nivelpadre_id="1"/>

    <!-- Municipios de Cachapoal -->
    <gis_zone enabled="true" id="5" code="5"
        name="Codegua" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="6" code="6"
        name="Coinco" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="7" code="7"
        name="Coltauco" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="8" code="8"
        name="Doñihue" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="9" code="9"
        name="Graneros" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="10" code="10"
        name="Las Cabras" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="11" code="11"
        name="Machalí" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="12" code="12"
        name="Malloa" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="13" code="13"
        name="Mostazal" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="14" code="14"
        name="Olivar" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="15" code="15"
        name="Peumo" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="16" code="16"
        name="Pichidegua" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="17" code="17"
        name="Quinta de Tilcoco" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="18" code="18"
        name="Rancagua" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="19" code="19"
        name="Rengo" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="20" code="20"
        name="Requínoa" type="M" nivelpadre_id="2"/>
    <gis_zone enabled="true" id="21" code="21"
        name="San Vicente de Tagua Tagua" type="M" nivelpadre_id="2"/>

    <!-- municipios de Cardenal Caro -->
    <gis_zone enabled="true" id="22" code="22"
        name="La Estrella" type="M" nivelpadre_id="4"/>
    <gis_zone enabled="true" id="23" code="23"
        name="Litueche" type="M" nivelpadre_id="4"/>
    <gis_zone enabled="true" id="24" code="24"
        name="Marchihue" type="M" nivelpadre_id="4"/>
    <gis_zone enabled="true" id="25" code="25"
        name="Navidad" type="M" nivelpadre_id="4"/>
    <gis_zone enabled="true" id="26" code="26"
        name="Paredones" type="M" nivelpadre_id="4"/>
    <gis_zone enabled="true" id="27" code="27"
        name="Pichilemu" type="M" nivelpadre_id="4"/>
    <!-- Municipios de Colchagua -->
    <gis_zone enabled="true" id="28" code="28"
        name="Chépica" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="29" code="29"
        name="Chimbarongo" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="30" code="30"
        name="Lolol" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="31" code="31"
        name="Nancagua" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="32" code="32"
        name="Palmilla" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="33" code="33"
        name="Peralillo" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="34" code="34"
        name="Placilla" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="35" code="35"
        name="Pumanque" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="36" code="36"
        name="San Fernando" type="M" nivelpadre_id="3"/>
    <gis_zone enabled="true" id="37" code="37"
        name="Santa Cruz" type="M" nivelpadre_id="3"/>




    <gis_authority name="I. Municipalidad de Chepica" id="1"
        zone_id="28" auth_type_id="1" create_date="2012-10-02 16:27:49.250453" update_date="2012-10-02 16:27:49.250453" />
    <gis_authority name="I. Municipalidad de Chimbarongo"
        id="2" zone_id="29" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Codegua" id="3"
        zone_id="5" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Coinco" id="4"
        zone_id="6" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Coltauco"
        id="5" zone_id="7" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Doñihue" id="6"
        zone_id="8" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Graneros"
        id="7" zone_id="9" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de La Estrella"
        id="8" zone_id="22" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Las Cabras"
        id="9" zone_id="10" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Litueche"
        id="10" zone_id="23" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Lolol" id="11"
        zone_id="30" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Machalí" id="12"
        zone_id="11" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Malloa" id="13"
        zone_id="12" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Marchigue"
        id="14" zone_id="24" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Mostazal"
        id="15" zone_id="13" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Nancagua"
        id="16" zone_id="31" auth_type_id="1" create_date="2012-12-10 17:30:49.250453" update_date="2012-12-10 17:30:49.250453" />
    <gis_authority name="I. Municipalidad de Navidad" id="17"
